### ISSUE TITLE
Restful API Authentication

### ISSUE THREAD

**Issue by jeffny2015** [pythononwheels/pow_devel#45]
Hi,

I want to know what is the best option to implement authentication in pythononwheels restful api ???

**Comment by pythononwheels** [comment]
Hi,

standard approach would be to:

Generate a user model with the needed attributes like name, email, password, login_name etc.
python generate_model.py -n user -t <yourdDB>
Then generate a user `REST `handler to manage users as an admin (create update delete...)
use generate_scaffold -n user to generate the according management views automatically-
python generate_handler.py -name user -t <yourDB> --rest

To really authenticate users you have to make a login/register view.
Add `login `and `register `methods with routes of your choice to the user handler.

python generate_view.py --name login

You can use AJAX in the login/register view and form to react to errors without leaving the site.
E.g. show an error message etc. You can choose whichever library you prefer.

Sample Login method in user handler
```
 @route(r"/user/login", dispatch=["post"])
    def login(self):
        try:
            data_json = json.loads(self.request.body)
            ....
```


Make sure you encrypt the passwords before storing them in your DB and use HTTPS.
Every PythonOnWheels handler has the methods:

`generate_password_hash("password_plain`")`

and 

`check_password_hash(encrypted_passwd_from_db, "plaintext_passwd")`

returns True or False 

This is from the Werkzeug.security library:
https://werkzeug.palletsprojects.com/en/1.0.x/utils/#module-werkzeug.security

**Comment by jeffny2015** [comment]
I think im steel lost, what i want to implement is oauth 2 in my restful API(this api it justs works sending request an only json responses "no GUI application") any idea?

**Comment by pythononwheels** [comment]
OK, I see.. You want to act as an oauth v2 server or do you want to enable your app to user 3rd parties via oauth v2 authentication. Like loggin in with google or twitter to your app ?

**Comment by jeffny2015** [comment]
if i can get both options hehehe
i was thinking to use google but if i can get options   act as an oauth v2 provider or 3rd parties via oauth v2

**Comment by pythononwheels** [comment]
it should be relatively easy to integrate other oauth2 providers like google or twitter, facebook etc.
Since PythonOnWheels is based on tornado you can use this as a guideline:

[oauth2 google sample](https://www.tornadoweb.org/en/stable/auth.html#google)
