### ISSUE TITLE
Dash integration with pythononwheels is broken due to Werkzeug

### ISSUE THREAD

**Issue by smoy** [pythononwheels/pow_devel#51]
With pythononwheels==0.925.51, the dash tutorial is broken due to unpinned dependency on Werkzeug

cited on https://github.com/plotly/dash/issues/1992

Nothing specific with pythononwheels; however, for someone to follow the current dash on pythononwheels will fail.

In order to workaround the problem, I have to pip install a compatible version

```pip install Werkzeug==2.0.3```

**Comment by pythononwheels** [comment]
Hi @smoy,
thanks for the info. 
I will pin Werkzeug==2.0.3 to the requirements.

**Comment by pythononwheels** [comment]
merged your pull request. 
Thanks again for the info and solution.
